name: rei
favicon: null
layout_spectrum: 0.44160406780429184
typography_spectrum: 0.8314781929366291
title: Musings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6243155875708908
  lightness: 0.6247986857779324
  saturation: 0.6984968576580286
  rhythmicContrast: 0.5572648881934583
purpose: []
