name: rei
favicon: null
layout_spectrum: 0.09806
typography_spectrum: 0.42616
title: Musings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b0940'
    - '#ffffff'
    - '#a2a0ac'
    - '#716886'
    - '#4e3757'
  brandStrength: 0.6243155875708908
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
